# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/twpayne/go-pinentry
%global goipath         github.com/twpayne/go-pinentry
Version:                0.2.0

%gometa

%global common_description %{expand:
Package pinentry provides a client to GnuPG's pinentry.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Package pinentry provides a client to GnuPG's pinentry

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires: golang(github.com/golang/mock/gomock)

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
